### ISSUE TITLE
如何得到HOTA

### ISSUE THREAD

**Issue by xun9167** [JackWoo0831/DepthMOT#3]
在visdrone-test数据集上运行track之后，得到result文件，里面包含数个.txt文件
![image](https://github.com/JackWoo0831/DepthMOT/assets/57390064/eca91853-6f67-4e15-a318-ae848e935d02)
qing请问如何通过这些txt文件，得到论文中的HOTA数据

**Comment by JackWoo0831** [comment]
我是用TrackEval库计算的，我这个repo中有对VisDrone的支持[https://github.com/JackWoo0831/Easier_To_Use_TrackEval](https://github.com/JackWoo0831/Easier_To_Use_TrackEvall)
